Volen lligar-te a un discurs, a una bandera
Tot el que eres seràs
Volen nugar-te a una marca, a una idea
Volen que digues si és negre o si és blanc
Volen la nit de la vida
La volen buida, no volen vore't dubtar
Volen quietut i la volen indefinida
Volen la seguretat
Ser d'este món és un poc complicat
Ser i no ser-ho de forma normal
Baix del meu llit tonelades de tristesa
Em queda bé la disfressa de sant?
De què estàs fugint quan acuses?
Les teues paraules on van?
Quan no quede res, tampoc hi haurà excuses
Tornen les hòsties com un boomerang
Ara és blaneta la pedra
Ara fa un fred tropical
S'han fet de pau i de guerra
Totes les contradiccions
I les cançons, ventiladors
Que esguiten merda, merda pa' tots
Deixa que et cante la carta, tenim de tot
De qualitat normaleta
Li pose tot el carinyo, baixa eixe foc
Volen la base ben feta
Si a mi se'm talla la salsa, un nou bufó
Mai menjaré de calent
He de mantindre esta farsa, qui paga mana
Sóc jo o son ells els clients?
Volen paraules com armes, dignes i plenes
Que òbrigues cor i cartera
Volen metàfores i actes, drama i teatre
Volen titella i trinxera
Volen que passes l'examen que ells posen
Volen ser jutges i autoritat
Volen que dones la pasta que guanyes
Diguem-ho clar: volen manar
Deixa que traga l'ego a subasta
Ja prou d'escriure i pensar a la carta
Deixa que diga el que pensa el dimoni dormit
Deixa que em lleve el vestit
Somiaven feres dormides, frases domades
Líriques subordinades
Plats ben calents, postres gelats
Volien merda i tenen Raval
Ara és blaneta la pedra
Ara fa un fred tropical
S'han fet de pau i de guerra
Totes les contradiccions
I les cançons, ventiladors
Que esguiten merda, merda pa' tots
Volen i volen, no solen buidar
Tot ho controlen, el bé i el mal
Eixa és la fórmula, este és un fals
Eixes no molen, no em fan volar
Eixa has fallat la teoria i la canviaria
Esta és un poc regular
Esta està bé, però es nota l'hipocresia
I a esta li falla el final
Critica i ataca
Mira la butxaca
Heroi sense capa
Lo que diga el negrata
Ara és blaneta la pedra
Ara fa un fred tropical
S'han fet de pau i de guerra
Totes les contradiccions
I les cançons, ventiladors
Que esguiten merda, merda pa' tots
Ara és blaneta la pedra
Ara fa un fred tropical
S'han fet de pau i de guerra
Totes les contradiccions
I les cançons, ventiladors
Que esguiten merda, merda pa' tots
